Controllers/ExcelController.cs
using ExcelDataReader;
using HPIMS_MVC_SignalR_Integrated.Excel_Import;
using HPIMS_MVC_SignalR_Integrated.Models;
using HPIMS_MVC_SignalR_Integrated.Models_MiddleLayer;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace HPIMS_MVC_SignalR_Integrated.Controllers
{
    public class ExcelController : Controller
    {
        private readonly ExcelContext _dbContext;
        public ExcelController()
        {
            _dbContext = new ExcelContext();
        }


        // Notification - Excel Data Import

        [HttpPost]
        public async Task<ActionResult> ImportNotificationFile(HttpPostedFileBase importFile)
        {
            if (importFile == null) return Json(new { Status = 0, Message = "No File Selected" });

            try
            {
                var fileData = NotificationCSVFile(importFile.InputStream);

                var notificationData = fileData.ToDataTable();
                var tableParameter = new SqlParameter("ExcelDataObject", SqlDbType.Structured)
                {
                    TypeName = "dbo.NotificationExcelType",
                    Value = notificationData
                };
                await _dbContext.Database.ExecuteSqlCommandAsync("EXEC NotificationExcelProcedure @ExcelDataObject", tableParameter);
                return Json(new { Status = 1, Message = "File Imported Successfully " });
            }
            catch (Exception ex)
            {
                return Json(new { Status = 0, Message = ex.Message });
            }
        }

        private List<NotificationModel> NotificationCSVFile(Stream stream)
        {
            var dataList = new List<NotificationModel>();
            try
            {
                using (var reader = ExcelReaderFactory.CreateCsvReader(stream))
                {
                    var dataSet = reader.AsDataSet(new ExcelDataSetConfiguration
                    {
                        ConfigureDataTable = _ => new ExcelDataTableConfiguration
                        {
                            UseHeaderRow = true // To set First Row As Column Names    
                        }
                    });

                    if (dataSet.Tables.Count > 0)
                    {
                        var dataTable = dataSet.Tables[0];
                        foreach (DataRow objDataRow in dataTable.Rows)
                        {
                            if (objDataRow.ItemArray.All(x => string.IsNullOrEmpty(x?.ToString()))) continue;
                            dataList.Add(new NotificationModel()
                            {
                                Id = Convert.ToInt32(objDataRow["Id"].ToString()),
                                Type = objDataRow["Type"] != DBNull.Value ? objDataRow["Type"].ToString() : "",
                                Subject = objDataRow["Subject"] != DBNull.Value ? objDataRow["Subject"].ToString() : "",
                                MessageBody = objDataRow["MessageBody"] != DBNull.Value ? objDataRow["MessageBody"].ToString() : "",
                                IsActive = objDataRow["IsActive"].ToString() != "" ? Convert.ToBoolean(objDataRow["IsActive"].ToString()) : false,
                            });
                        }
                    }
                }
            }
            catch (Exception)
            {
                throw;
            }
            return dataList;
        }

        // Notification Mapping - Excel Data Import

        [HttpPost]
        public async Task<ActionResult> ImportNMFile(HttpPostedFileBase importFile)
        {
            if (importFile == null) return Json(new { Status = 0, Message = "No File Selected" });

            try
            {
                var fileData = NMCSVFile(importFile.InputStream);

                var nmData = fileData.ToDataTable();
                var tableParameter = new SqlParameter("ExcelDataObject", SqlDbType.Structured)
                {
                    TypeName = "dbo.NMExcelType",
                    Value = nmData
                };
                await _dbContext.Database.ExecuteSqlCommandAsync("EXEC NMExcelProcedure @ExcelDataObject", tableParameter);
                return Json(new { Status = 1, Message = "File Imported Successfully " });
            }
            catch (Exception ex)
            {
                return Json(new { Status = 0, Message = ex.Message });
            }
        }

        private List<NotificationMappingModel> NMCSVFile(Stream stream)
        {
            var dataList = new List<NotificationMappingModel>();
            try
            {
                using (var reader = ExcelReaderFactory.CreateCsvReader(stream))
                {
                    var dataSet = reader.AsDataSet(new ExcelDataSetConfiguration
                    {
                        ConfigureDataTable = _ => new ExcelDataTableConfiguration
                        {
                            UseHeaderRow = true // To set First Row As Column Names    
                        }
                    });

                    if (dataSet.Tables.Count > 0)
                    {
                        var dataTable = dataSet.Tables[0];
                        foreach (DataRow objDataRow in dataTable.Rows)
                        {
                            if (objDataRow.ItemArray.All(x => string.IsNullOrEmpty(x?.ToString()))) continue;
                            dataList.Add(new NotificationMappingModel()
                            {
                                Id = Convert.ToInt32(objDataRow["Id"].ToString()),
                                ServerId = objDataRow["ServerId"] != DBNull.Value ? Convert.ToInt32(objDataRow["ServerId"].ToString()) : Convert.ToInt32(null),
                                ProjectId = objDataRow["ProjectId"] != DBNull.Value ? Convert.ToInt32(objDataRow["ProjectId"].ToString()) : Convert.ToInt32(null),
                                NotificationId = objDataRow["NotificationId"] != DBNull.Value ? Convert.ToInt32(objDataRow["NotificationId"].ToString()) : Convert.ToInt32(null),
                                ToAddress = objDataRow["ToAddress"] != DBNull.Value ? objDataRow["ToAddress"].ToString() : "",
                                CCAddress = objDataRow["CCAddress"] != DBNull.Value ? objDataRow["CCAddress"].ToString() : "",
                                BCCAddress = objDataRow["BCCAddress"] != DBNull.Value ? objDataRow["BCCAddress"].ToString() : "",
                                IsActive = objDataRow["IsActive"].ToString() != "" ? Convert.ToBoolean(objDataRow["IsActive"].ToString()) : false,
                            });
                        }
                    }
                }
            }
            catch (Exception)
            {
                throw;
            }
            return dataList;
        }

        // Project - Excel Data Import

        [HttpPost]
        public async Task<ActionResult> ImportProjectFile(HttpPostedFileBase importFile)
        {
            if (importFile == null) return Json(new { Status = 0, Message = "No File Selected" });

            try
            {
                var fileData = ProjectCSVFile(importFile.InputStream);

                var projectData = fileData.ToDataTable();
                var tableParameter = new SqlParameter("ExcelDataObject", SqlDbType.Structured)
                {
                    TypeName = "dbo.ProjectExcelType",
                    Value = projectData
                };
                await _dbContext.Database.ExecuteSqlCommandAsync("EXEC ProjectExcelProcedure @ExcelDataObject", tableParameter);
                return Json(new { Status = 1, Message = "File Imported Successfully " });
            }
            catch (Exception ex)
            {
                return Json(new { Status = 0, Message = ex.Message });
            }
        }

        private List<ProjectModel> ProjectCSVFile(Stream stream)
        {
            var dataList = new List<ProjectModel>();
            try
            {
                using (var reader = ExcelReaderFactory.CreateCsvReader(stream))
                {
                    
                    var dataSet = reader.AsDataSet(new ExcelDataSetConfiguration
                    {
                        ConfigureDataTable = _ => new ExcelDataTableConfiguration
                        {
                            UseHeaderRow = true // To set First Row As Column Names    
                        }
                    });

                    if (dataSet.Tables.Count > 0)
                    {
                        var dataTable = dataSet.Tables[0];
                        foreach (DataRow objDataRow in dataTable.Rows)
                        {
                            if (objDataRow.ItemArray.All(x => string.IsNullOrEmpty(x?.ToString()))) continue;
                            dataList.Add(new ProjectModel()
                            {
                                Id = Convert.ToInt32(objDataRow["Id"].ToString()),
                                ProjectName = objDataRow["ProjectName"] != DBNull.Value ? objDataRow["ProjectName"].ToString() : "",
                                Version = objDataRow["Version"] != DBNull.Value ? objDataRow["Version"].ToString() : "",
                                Status = objDataRow["Status"] != DBNull.Value ? objDataRow["Status"].ToString() : "",
                                IsActive = objDataRow["IsActive"].ToString() != "" ? Convert.ToBoolean(objDataRow["IsActive"].ToString()) : false,
                            });
                        }
                    }
                }
            }
            catch (Exception)
            {
                throw;
            }
            return dataList;
        }

        // Project Server Mapping - Excel Data Import

        [HttpPost]

Controllers/ProjectServerMappingController.cs
using HPIMS_MVC_SignalR_Integrated.Models;
using HPIMS_MVC_SignalR_Integrated.Models_MiddleLayer;
using System.Web.Mvc;

namespace HPIMS_MVC_SignalR_Integrated.Controllers
{
    public class ProjectServerMappingController : Controller
    {
        ProjectServerMappingMiddleLayer PSMML = new ProjectServerMappingMiddleLayer();
        public ActionResult ProjectServerMappingList()
        {
            return View(PSMML.GetDataList());
        }
        public ActionResult Details(int Id)
        {
            return View(PSMML.GetDataList().Find(PSMM => PSMM.Id == Id));
        }
        public ActionResult Create()
        {
            ViewBag.ServerData = new SelectList(PSMML.GetPartialServerList(),"Id", "ServerName");
            ViewBag.ProjectName = new SelectList(PSMML.GetPartialProjectList(), "Id", "ProjectName");
            return View();
        }
        [HttpPost]
        public ActionResult Create(ProjectServerMappingModel PSMM)
        {
            try
            {
                if (PSMML.InsertData(PSMM))
                {
                    ViewBag.Message = "Data Saved";
                }
                return RedirectToAction("ProjectServerMappingList", "ProjectServerMapping");
            }
            catch
            {
                return View();
            }
        }
        public ActionResult Edit(int Id)
        {
            ViewBag.ServerData = new SelectList(PSMML.GetPartialServerList(), "Id", "ServerName");
            ViewBag.ProjectName = new SelectList(PSMML.GetPartialProjectList(), "Id", "ProjectName");
            return View(PSMML.GetDataList().Find(PSMM => PSMM.Id == Id));
        }
        [HttpPost]
        public ActionResult Edit(int Id, ProjectServerMappingModel PSMM)
        {
            try
            {
                if (PSMML.UpdateData(PSMM))
                {
                    ViewBag.Message = "Data Updated";
                }
                return RedirectToAction("ProjectServerMappingList", "ProjectServerMapping");
            }
            catch
            {
                return View();
            }
        }
        public ActionResult Delete(int Id)
        {
            return View(PSMML.GetDataList().Find(PSMM => PSMM.Id == Id));
        }
        [HttpPost]
        public ActionResult Delete(int Id, ProjectServerMappingModel PSMM)
        {
            try
            {
                if (PSMML.DeleteData(PSMM))
                {
                    ViewBag.Message = "Data Deleted";
                }
                return RedirectToAction("ProjectServerMappingList", "ProjectServerMapping");
            }
            catch
            {
                return View();
            }
        }
    }
}

Views/ProjectServerMapping/Create.cshtml
@model HPIMS_MVC_SignalR_Integrated.Models.ProjectServerMappingModel
@{
    ViewBag.Title = "Add Information";
}

<div class="container">
    <br />
    <h4 style="font-weight:600">Add Data:</h4>
    <h5 style="font-style:italic;font-weight:300">Enter information in the field and click save to add data.</h5>
    <hr />
    <div style="text-align:right">
        <a class="btn btn-outline-success" role="button" style="text-decoration:none" href="@Url.Action("ProjectServerMappingList","ProjectServerMapping")">
            Back to List
        </a>
    </div>
    <br />

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div>
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <table class="table table-borderless">
                <tr>
                    <td style="font-weight:600">
                        @Html.LabelFor(model => model.ServerId, htmlAttributes: new { @class = "control-label col-md-4" })
                    </td>
                    <td>
                        @Html.DropDownListFor(model => model.ServerId, ViewBag.ServerData as SelectList, "Select", new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.ServerId, "", new { @class = "text-danger" })
                    </td>
                </tr>
                <tr>
                    <td style="font-weight:600">
                        @Html.LabelFor(model => model.ProjectId, htmlAttributes: new { @class = "control-label col-md-4" })
                    </td>
                    <td>
                        @Html.DropDownListFor(model => model.ProjectId, ViewBag.ProjectName as SelectList, "Select", new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.ProjectId, "", new { @class = "text-danger" })
                    </td>
                </tr>
                <tr>
                    <td style="font-weight:600">
                        @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-4" })
                    </td>
                    <td>
                        @Html.EditorFor(model => model.IsActive)
                    </td>
                </tr>
            </table>

            <hr />
            <input type="submit" value="Save" class="btn btn-outline-success btn-lg" />
        </div>
    }

</div>
<br />

Views/ProjectServerMapping/Delete.cshtml
@model HPIMS_MVC_SignalR_Integrated.Models.ProjectServerMappingModel

@{
    ViewBag.Title = "Delete Data";
}
<div class="container">
    <br />
    <h4 style="font-weight:600">Delete Data:</h4>
    <h5 style="font-style:italic;font-weight:300">Data will be permanently deleted. Would you like to continue?</h5>

    <hr />
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color" style="text-align:right">
            <input type="submit" value="Delete" class="btn btn-outline-danger" />
            <a class="btn btn-outline-success" role="button" style="text-decoration:none" href="@Url.Action("ProjectServerMappingList","ProjectServerMapping")">
                Back to List
            </a>
        </div>
    }
    <br />
</div>

Views/ProjectServerMapping/Details.cshtml
@model HPIMS_MVC_SignalR_Integrated.Models.ProjectServerMappingModel

@{
    ViewBag.Title = "Details";
}

<div class="container">
    <br />
    <h4 style="font-weight:600">Project Server Mapping Details:</h4>
    <h5 style="font-style:italic;font-weight:300">Click on the Edit button to make changes.</h5>
    <hr />
    <div style="text-align:right">
        <a class="btn btn-outline-warning" role="button" style="text-decoration:none" href="@Url.Action("Edit","ProjectServerMapping", new {id = Model.Id})">
            Edit
        </a>
        <a class="btn btn-outline-success" role="button" style="text-decoration:none" href="@Url.Action("ProjectServerMappingList","ProjectServerMapping")">
            Back to List
        </a>
    </div>
    <br />

    <div>
        <table class="table table-bordered" style="text-align:center">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Id)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ServerId)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ProjectId)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.IsActive)
                </th>
            </tr>
            <tr>

                <td>
                    @Html.DisplayFor(model => model.Id)
                </td>
                <td>
                    @Html.DisplayFor(model => model.ServerId)
                </td>
                <td>
                    @Html.DisplayFor(model => model.ProjectId)
                </td>
                <td>

                    @{
                        if (Model.IsActive)
                        {
                            <img src="~/Images/Icon/Active - Green.png" height="20" width="20" />
                        }
                        else
                        {
                            <img src="~/Images/Icon/Active - Red.png" height="20" width="20" />
                        }
                    }
                </td>
            </tr>
        </table>
    </div>
</div>

Views/ProjectServerMapping/Edit.cshtml
@model HPIMS_MVC_SignalR_Integrated.Models.ProjectServerMappingModel

@{
    ViewBag.Title = "Edit Data";
}
<div class="container">
    <br />
    <h4 style="font-weight:600">Edit Data:</h4>
    <h5 style="font-style:italic;font-weight:300">Enter information to make changes.</h5>

    <hr />
    <div style="text-align:right">
        <a class="btn btn-outline-success" role="button" style="text-decoration:none" href="@Url.Action("ProjectServerMappingList","ProjectServerMapping")">
            Back to List
        </a>
    </div>
    <br />

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div>
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)
            <table class="table table-borderless">
                <tr>
                    <td style="font-weight:600">
                        @Html.LabelFor(model => model.ServerId, htmlAttributes: new { @class = "control-label col-md-4" })
                    </td>
                    <td>
                        @Html.DropDownListFor(model => model.ServerId, ViewBag.ServerData as SelectList, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.ServerId, "", new { @class = "text-danger" })
                    </td>
                </tr>
                <tr>
                    <td style="font-weight:600">
                        @Html.LabelFor(model => model.ProjectId, htmlAttributes: new { @class = "control-label col-md-4" })
                    </td>
                    <td>
                        @Html.DropDownListFor(model => model.ProjectId, ViewBag.ProjectName as SelectList, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.ProjectId, "", new { @class = "text-danger" })
                    </td>
                </tr>
                <tr>
                    <td style="font-weight:600">
                        @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-4" })
                    </td>
                    <td>
                        @Html.EditorFor(model => model.IsActive)
                    </td>
                </tr>
            </table>

            <hr />
            <input type="submit" value="Update Details" class="btn btn-outline-success btn-lg" />
        </div>
    }

</div>
<br />

Views/ProjectServerMapping/ProjectServerMappingList.cshtml
@model IEnumerable<HPIMS_MVC_SignalR_Integrated.Models.ProjectServerMappingModel>

@{
    ViewBag.Title = "Project-Server Mapping";
}

<div class="container-fluid" style="padding-left:10px;padding-right:10px">
    <br />
    <h3 style="font-style:italic ; padding-top: 0px; margin-bottom:0px">Project-Server Mapping Data</h3>
    <div class="row justify-content-end">
        <div class="col-1" style="padding-right:0">
            <a class="btn btn-outline-primary btn-sm" role="button" style="text-decoration:none" href="@Url.Action("Create","ProjectServerMapping")">Add Data</a>
        </div>
        <div class="col-2" style="padding-right:1px; padding-left:0px">
            <input class="form-control btn-sm" type="file" name="importFile" id="importFile" />
        </div>
        <div class="col-1" style="padding-left:2px">
            <button id="btnUpload" type="button" class="button"><span class="button__text">Upload</span></button>
        </div>
    </div>
    <br />
    <div>
        <table class="table" style="text-align:center; font-size: 13px">
            <thead style="text-align:center">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Id)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.ServerId)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.ProjectId)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.IsActive)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td style="text-align:center">
                            @Html.DisplayFor(modelItem => item.Id)
                        </td>
                        <td style="text-align:center">
                            @Html.DisplayFor(modelItem => item.ServerId)
                        </td>
                        <td style="text-align:center">
                            @Html.DisplayFor(modelItem => item.ProjectId)
                        </td>
                        <td style="text-align:center">

                            @{
                                if (item.IsActive)
                                {
                                    <img src="~/Images/Icon/Active - Green.png" height="15" width="15" />
                                }
                                else
                                {
                                    <img src="~/Images/Icon/Active - Red.png" height="15" width="15" />
                                }
                            }


                        </td>
                        <td>
                            <a role="button" style="text-decoration:none" href="@Url.Action("Edit","ProjectServerMapping", new { id = item.Id })"><img src="~/Images/Icon/Edit.png" height="20" width="20"></a>
                            <a role="button" style="text-decoration:none" href="@Url.Action("Details","ProjectServerMapping", new { id = item.Id })"><img src="~/Images/Icon/Details.png" height="20" width="20"></a>
                            <a role="button" style="text-decoration:none" href="@Url.Action("Delete","ProjectServerMapping", new { id = item.Id })"><img src="~/Images/Icon/Delete.jpg" height="20" width="20"></a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

@section scripts{
    <script>
        const clicking = document.querySelector(".button");
        $(document).on("click", "#btnUpload", function () {
            clicking.classList.add("button--loading");

            var files = $("#importFile").get(0).files;
            var formData = new FormData();
            formData.append('importFile', files[0]);

            $.ajax({
                url: '@(Url.Action("ImportPSMFile", "Excel"))',
                data: formData,
                type: 'POST',
                contentType: false,
                processData: false,
                success: function (data) {
                    if (data.Status === 1) {
                        clicking.classList.remove("button--loading");
                        alert(data.Message);
                        location.reload();
                    } else {
                        clicking.classList.remove("button--loading");
                        alert(data.Message);
                        location.reload();
                    }
                }
            });
        });
    </script>
}